# Generated by Django 4.2.28 on 2026-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Sales'), ('expense', 'Expense')], default='sale', max_length=20),
        ),
    ]
