# Generated by Django - data migration

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_system_user_and_backfill(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    JournalEntry = apps.get_model('journal', 'JournalEntry')

    system_user, created = User.objects.get_or_create(
        username='system',
        defaults={
            'email': '',
            'password': make_password(None),
            'is_active': False,
            'is_staff': False,
            'is_superuser': False,
        }
    )
    if created and not system_user.password:
        system_user.password = make_password(None)
        system_user.save(update_fields=['password'])

    JournalEntry.objects.filter(created_by__isnull=True).update(created_by=system_user)
    JournalEntry.objects.filter(updated_by__isnull=True).update(updated_by=system_user)


def reverse_backfill(apps, schema_editor):
    JournalEntry = apps.get_model('journal', 'JournalEntry')
    JournalEntry.objects.all().update(created_by=None, updated_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_add_rbac_and_activity_log'),
    ]

    operations = [
        migrations.RunPython(create_system_user_and_backfill, reverse_backfill),
    ]
