# Google App Engine Standard - Django app
# See README "Deploy to Google App Engine" for setup steps.

runtime: python312

entrypoint: gunicorn -b :$PORT config.wsgi

env_variables:
  # Set SECRET_KEY in Google Cloud Console (App Engine > Settings > Environment variables)
  # or via: gcloud app deploy --set-env-vars SECRET_KEY=your-secret-key
  DEBUG: "False"
  # Replace with your App Engine URL after first deploy (e.g. your-app.uc.r.appspot.com)
  ALLOWED_HOSTS: "your-app.uc.r.appspot.com"
  # HTTPS origin for CSRF (match your app URL)
  CSRF_TRUSTED_ORIGINS: "https://your-app.uc.r.appspot.com"
  # Cloud SQL: set these in Console or here (do not commit real passwords to repo)
  # INSTANCE_CONNECTION_NAME: "PROJECT_ID:REGION:INSTANCE_NAME"
  # DJANGO_DB_NAME: "pure_herb_db"
  # DJANGO_DB_USER: "your_db_user"
  # DJANGO_DB_PASSWORD: "your_db_password"

# Uncomment and set to your Cloud SQL instance (project:region:instance) when using Cloud SQL
# beta_settings:
#   cloud_sql_instances: "PROJECT_ID:REGION:INSTANCE_NAME"
